### ISSUE TITLE
Copy code button is not working properly

### ISSUE THREAD

**Issue by SimplySmartHouse** [PxlSyl/tailwind-nextjs-starter-blog-i18n#25]
The copy code button is not working properly, it is aligned to the left instead of the right,
 it seems to be missing tailwind styles for some reason.

![Screenshot 2024-07-12 at 16 02 04](https://github.com/user-attachments/assets/efee6c33-29ff-4403-af2b-841dbe59d7d3)

Adding the missing styles to the tailwind.css file solves the issue:
```css
.right-2 {
  right: 0.5rem;
}

.top-2 {
  top: .5rem;
  }

.bg-gray-700 {
  --tw-bg-opacity: 1;
  background-color: rgb(55 65 81/var(--tw-bg-opacity));
  }

  .text-gray-300 {
    --tw-text-opacity: 1;
    color: rgb(209 213 219/var(--tw-text-opacity));
    }

    .border-green-400 {
      --tw-border-opacity: 1;
      border-color: rgb(74 222 128 / var(--tw-border-opacity));
  }

  .text-green-400 {
    --tw-text-opacity: 1;
    color: rgb(74 222 128 / var(--tw-text-opacity));
}
```

Not sure if that's the right solution, but it works as a workaround.

![Screenshot 2024-07-12 at 16 07 41](https://github.com/user-attachments/assets/f213ddbf-e03f-4110-8bb1-4f326005e781)
